version: "3"

services:
  myapp:
    build:
      context: ./container/myapp
    environment:
      - AWS_DEFAULT_REGION=ap-northeast-1
    volumes:
      - ./container/myapp:/var/task
    command: ["/bin/bash"]  # DockerfileのCMDを上書きし、ttyを有効化
    tty: true
